#!/bin/sh

start() {
        printf "Starting camera demo: "
        /root/demo 192.168.1.7 &
        echo "OK"
}
stop() {
        printf "Stopping camera demo: "
        killall demo
        echo "OK"
}
restart() {
        stop
        start
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        restart
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
